// vim: tw=79

:toc:

'''

= Tendrl Frontend: Deployment

Tendrl frontend is a static webapp, built from a Node.js project. This document
details how to build from the source, and then how to configure the webhost to
serve the app.

== Minimum System Requirement

This is the bare minimal requirements for a VM to be able to run the Tendrl frontend server. However, for performance and efficiency, more resources would be good to avail: 

* *CPU:* 1 core, 1 thread
* *RAM:* 512 MiB
* *Storage:* 10GiB
* *OS:* RHEL 7.x or similar

== Basic package dependencies

* apache/nginx (optional)

== Build dependencies

* git
* nodejs
* npm
** gulp
** tsd
** <add more>

== How to Deploy

To deploy Tendrl frontend, you may want to build from source, or install the package.

* *If installing from package*, skip the "Building from source" section
* *If building from source*, likewise, skip "Installing from repo" section

TIP: This entire process should be handled by a bootstrapping script in future.

NOTE: _The commands listed here assumes latest version of Fedora in use as the host OS, use proper substitution if your environment differ._

=== Step 1: Preparing host

==== If you're on *Fedora*
Nothing to do here, jump to next step.

==== If you're on *RHEL*
You need to register and activate your subscription with customer portal ID to add repos and install packages. _@TODO: process details & guides._

==== If you're on *CentOS*
You need to enable EPEL repo with `yum install epel-release`

==== If you're on *Other Distro*
Follow along the next steps, and depending on distros, some processes, commands and package names may vary.

=== Step 2: Building from source

First we need the essential packages

```sh
$ sudo dnf install -y git nodejs npm
```

Then we need the frontend source

```sh
$ git clone https://github.com/Tendrl/tendrl_frontend.git
$ cd tendrl_frontend
```

Next we will install the dependencies for the package to build

```sh
$ sudo npm install -g gulp tsd
$ npm install
$ tsd install
```

Lastly, the build... which is an one step process, using gulp to automate the underlying steps
```sh
$ gulp compile
```

Once gulp finishes compiling, the build artifacts will be available in the `dist` subdirectory within the source path.

=== Step 3: Installing from repo

_@TODO: content to be added when package details are available._

=== Step 4: Serving the application

In this step, we take the build artifacts and serve them as web contents.

_@TODO: if installed from package, depending on which all steps are covered in the process, this section might need updating._

---

==== Configure firewall

For the server to be able to accept and serve external http requests, we need to configure the firewall.

This isn't required to be the first step (and can be done after installing/running the webserver), however, this is a common step for whatever webserver we choose to go with up next.

```sh
$ sudo firewall-cmd --permanent --zone=public --add-service=http
$ sudo firewall-cmd --reload
```

---

==== Serve using nginx

First, let's install and start `nginx`

```sh
$ sudo dnf install -y nginx
$ sudo systemctl start nginx
```

At this point, you should be able to see the default nginx web page, by visiting `http://<hostname.or.ip.address>/` from your browser.

Now, to serve the app content (instead of the default page) you can take either of the 2 following ways (among many other possible, less desirable ways):

. *Easy way:* copy over app contents to nginx's default webroot
.. Backup the default pages: `$ sudo mv /usr/share/nginx/html /usr/share/nginx/default`
.. Copy over the app contents: `$ cp -r <source-path>/dist /usr/share/nginx/html`
. *Right way:* follow along https://www.nginx.com/resources/admin-guide/serving-static-content/[nginx's official documentation] on how to configure the server for serving static webapp.

---

==== Serve using httpd

Again, let's install and start Apache first

```sh
$ sudo dnf install -y httpd
$ sudo systemctl start httpd
```

At this point, you should be able to see the default httpd web page, by visiting `http://<hostname.or.ip.address>/` from your browser.

Now, to serve the app content (instead of the default page) you can take either of the 2 following ways (among many other possible, less desirable ways):

. *Easy way:* copy over app contents to httpd's default webroot: `$ cp -r <source-path>/dist/* /var/www/html/`
. *Right way:* follow along https://httpd.apache.org/docs/trunk/configuring.html[Apache's official documentation] on how to configure the server for serving static webapp.

---

If everything went well, at this point browing `http://<hostname.or.ip.address>/` from your web-browser should give you Tendrl's frontend landing page.

'''

_@TODO: update doc to run the app over HTTPS_
