// vim: tw=79
= Tendrl Documentation

Welcome to the documentation repository of the Tendrl project!

This repository is intended to host documentation for the entire project. It
covers design and architecture notes; developer workflow detail and similar.
Notes and documentation specific to the code-base as well as of significance
to a developer would be hosted in the same repository as the code


== Navigation

* https://github.com/Tendrl/documentation/blob/master/glossary.adoc[Glossary]
  defines all the terms referenced throughout the documentation. Keep it handy
  as a reference.
* https://github.com/Tendrl/documentation/blob/master/tendrl-architectural-guidelines.adoc[Architectural
  Guidelines] explains the architectural decisions.
* https://github.com/Tendrl/documentation/blob/master/tendrl-core-components-overview.adoc[Tendrl
  Core Components Overview] describes the various components in the Core Stack.


== How to use this repository?

The development workflow document (development-workflow.adoc) applies to any
changes to the contents of this repository, as it does to any of the Tendrl
project codebases.

Should you want to send a pull request against this repository, please follow
these guidelines:

* Configure your editor to use a hard line break on 79 characters.
* Don't delete the vim modeline comment at the top of the files.
* Feel free to add editor specific configuration to the files you author. Just
  ensure that it doesn't break the asciidoc syntax ie. ensure that it's in a
  comment.
* Use http://asciidoctor.org[asciidoctor] to validate the HTML output produced
  by the files you've written before committing them.

If you've never written asciidoc before, the
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[asciidoctor syntax
reference] is the best place to start. Jump into the more detailed
http://asciidoctor.org/docs/user-manual/[user manual] as you realize the need
for a feature beyond text formatting.
