// vim: tw=79
= Overview
----
:toc:
----

Tendrl provides APIs accessible via HTTP(s).
The API exposes operations for managing multiple enterprise storage providers with a single unified interface. 

Most API endpoints provides a list of actions and/or operations which can be 
performed depending on the nature of the resource. This approach prevents the
consumer from manually constructing the URL's and also automatically adapting
to functanality which might be added later or removed. 

The API provides actions and attributes for each kind of resource which contains 
mandatory attributes, optional attributes and validation rules which need to be
satisfied to create a valid resource. 

=== Versioning
The API will support versioning when there are breaking changes across 
releases.

The current version is 1.0

The version numbers are a part of the url so the base url for the current 
version would be
--------------
curl http://127.0.0.1/api/1.0
--------------

=== JSON Schema

The API can be accessed over http(s) and all the data is sent and received over
json.

Every request needs to set the content-type header to application/json.
----------
curl -H "Content-Type: application/json" http://127.0.0.1/api/1.0/ping
----------

==== Timestamps

All timestamps will be in iso8601 format.
----------
YYYY-MM-DDTHH:MM:SSZ
----------
=== Client Errors

There are three types of client errors 

1) Sending a invalid JSON will result in a `400 Bad Request` response.

2) Sending wrong type of JSON values will result in a `400 Bad Request` 
response.

3) Sending invalid fields will result in a `422 Unprocessable Entity` 
response. 

=== HTTP Verbs

The API expects the appropriate HTTP verbs for every action.

`HEAD` to retrieve the HTTP header info.

`GET` to retrieve a resource or multiple resources.

`POST` to create a new resource.

`PUT` to update a single resource or collections.

`DELETE` to delete a resource

=== Authentication

The API token needs to be sent in every request in the header 
`Authorization: Tendrl <API_TOKEN>`. 

----------
curl -H "Authorization: Tendrl <API_TOKEN>" https://api.example.com/1.0
----------

=== Flows

The API provides list of flows which can be performed either globally or on a specific resource. The flows provide the url, http method and attributes needed for a specific flow. For ex: Getting list of available flows.

----------
curl -XGET http://127.0.0.1/api/1.0/Flows
----------

=== User Agent

Every API request must send a `User-Agent` property in the header to identity 
the users. The User-Agent property should be the name of your application.

----------
curl -A "User-Agent: <APP_NAME>"
----------

=== Timezones

Every API request will use the user defined time zone as default. 
If you need the response in a specific time zone, you will have to send a 
`Time-Zone` header in the request which will be used to respond.

----------
curl -H "Time-Zone: Asia/Kolkata" -XGET https://api.example.com/1.0/
----------

=== Rate limiting

There is a limit of 5,000 requests per hour.
Exceeding the rate limit responds back with a `403 Forbidden` response.

=== Queuing

Some operations might take longer to complete, in which case the server 
responds back with a job key and a `202 Accepted` response.
The job key can be used to track the status of the requested operation.
